# Gradle Properties
org.gradle.jvmargs = -Xmx1G
org.gradle.parallel = true

# Mod Properties
version = 1.0.0
maven_group = com.LastEcho
archives_base_name = lastecho_npc

# Dependencies
retroapi_version = 0.3.7
retrocommands_version = 0.7.5
retrodragon_version = 0.1.12
retroconvert_version = 1.0.4

# Ornithe Related Dependencies - check https://ornithemc.net/develop for the latest versions
minecraft_version = b1.7.3
loader_version = 0.19.3

biny_mappings = 9859f76
client_raven_build = 2
server_raven_build = 2
client_sparrow_build = 2
server_sparrow_build = 2
biny_nests_build = 2

osl_version = 0.20.3
